### ISSUE TITLE
Data for Puerto Rico (done: production parser; ToDo: installed capacity, forecast parser)

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2530]
- [x] Add production parser - #2531 (need help with a few things)
- [ ] Add capacity data
- [ ] Add forecast parser<sup>Note: would marking 'unknown' renewable also affect the forecast? Because it shouldn't</sup>

---

* [Real-time generation data (+ forecast), updated every 30 minutes](https://aeepr.com/en-us/Pages/Generaci%C3%B3n.aspx)
  * Contains: 
     * Breakdown by fuel type: bunker C ([a type of fuel oil](https://en.wikipedia.org/wiki/Fuel_oil#United_States)), diesel, renewables, coal and natural gas
        * ***Click on the "renovables" part to view a [breakdown by renewable type](https://aeepr.com/es-pr/generacion/Documents/Unidades_renovables.aspx)***
     * Actual generation in MW
     * Generation forecast
* [Installed capacity](https://aeepr.com/es-pr/unidadesgeneratrices)  
  * Note that "Turbines gas" might include or even be 'Diesel GT', otherwise the large amount of generation from Diesel on the fuel type break down I'm seeing right now wouldn't make any sense (compared to the small amount of diesel generators listed).

The only thing that seems to be missing is hydro. It's listed on the _installed capacity_ page (separate from other renewables), but it doesn't seem present in the generation type  breakdown. The separate page with a breakdown of renewable generation doesn't list hydro either.  
At ​98.3MW installed capacity is pretty small though, so that shouldn't be a deal-breaker 

**Edit:** so it seems that wind/solar/landfill gas breakdown doesn't add up to the total generation from renewables. I assume that means the remainder is hydro

---

A few other possibly relevant things

https://aeepr.com/en-us/QuienesSomos/Pages/ElectricSystem.aspx contains the puzzling quote that "69 percent of production is from fuel" (renewable production isn't  even close to 31%). However, that seems about the amount generated right now from bunker + both types of diesel, so they probably mean generation from oil-based fuel and exclude nat. gas and coal.

https://aeepr.com/en-us/qui%C3%A9nes-somos/statisticalreports has links to various statistics. 1st link on this page takes you to https://aeepr.com/en-us/QuienesSomos/Pages/ley57/Estad%C3%ADsticos.aspx, which has annual reports

**Comment by q--** [comment]
Seems like the forecast/demand graph is updated later than the breakdown by generation type;

Right now _TIPOS DE COMBUSTIBLES_ is at 501+496+85+347+191+473 = 2093MW, and the bottom of the page says __Ultima Actualización: 05/30/2020 10:10:24 AM__

However, the forecast/demand graph is still at 9:40, for which it gives a demand of _2052.31_. The "Generacion Total" at the top of the page also gives 2052.31 MW

Will check once the demand/forecast graph has 10:10 if it matches what's currently visible on the demand graph

**Comment by q--** [comment]
I've stared work on a parser.

**Comment by q--** [comment]
I've started work on capacity data

[Capacity data page](https://aeepr.com/en-us/QuienesSomos/Pages/ElectricSystem.aspx) [Google Translate](https://aeepr.com/es-pr/unidadesgeneratrices)

The page lists the type of power station, but unfortunately not the fuel. So I've started going through the thermal power stations on the list to determine the fuel type.

# Power stations

## [PREPA-owned power stations](https://aeepr.com/es-pr/unidadesgeneratrices)

The mentioned fuel types "Residual # 6" and "Distilled # 2" seem to imply these plants are burning oil.

**Comment by Kongkille** [comment]
After the parser and the data source merge (#2878), I think we can close this issue and then potentially open another one in the future if there's more add :)
