### ISSUE TITLE
Expose Poetry package(s)

### ISSUE THREAD

**Issue by skovhus** [tmrowco/electricitymap-contrib#2970]
### Description
We are working on improving our internal mono repository setup using [Poetry](https://python-poetry.org/). It gives us some benefits: 
- deterministic dependency resolution
- intuitive CLI for scripts and dependency management
- a wrapper around virtual environment
- easier mono repository setup

By proxy, this will have some consequences for the development setup in `electricitymap-contrib`, but hopefully, we can make the installation steps here easier. 

Requirements to the `contrib` package(s):
- make it possible to load `config` without installing `parsers` dependencies (conceptually they are coupled)
- do not complicate the contributor workflow

### Options

I see two options:

#### 1. Multiple packages
Expose multiple packages (`electricitymap-contrib-config` and `electricitymap-contrib-parsers`). The `parsers` package would depend on `config`. First step is already done here: https://github.com/tmrowco/electricitymap-contrib/blob/master/config/pyproject.toml

Pros:
- easier to do narrow dependency tracking (e.g. did something change in the `config` folder)

Cons:
- due to namespace setup it would require the content of `parsers` to be moved to `parsers/electricitymap/contrib/parsers` (this is a rather big change and the code is also not as accessible). One alternative would be do do a new root folder `parser-package` which would symlink `parser-package/electricitymap/contrib/parsers` to `parsers` (but that is just confusing IMO)

#### 2. The one package to rule them all
One `electricitymap-contrib` containing both `config` and `parsers`, but all `parsers` dependencies are optional (using the `extras` feature).

Pros:
- less scaffolding and easier to manage
- fewer contribution changes
- simplifies the contribution setup (e.g. just one install command)

Prototype: https://github.com/tmrowco/electricitymap-contrib/pull/2971

### Tasks
- [x] Expose config as a Poetry package: https://github.com/tmrowco/electricitymap-contrib/pull/2940 
- [x] Investigate different options
- [x] Prototype mono package setup: https://github.com/tmrowco/electricitymap-contrib/pull/2971
- [x] Prototype multiple package setup: would require either new root folder or moving all parsers to a deeply nested folder
- [x] Wrap up prototype
- [x] Update documentation

### Definition of done
`electricitymap-contrib` is installable as Poetry package(s) and the contribution workflow isn't affected too much.

**Comment by corradio** [comment]
@skovhus should this be closed now?
